#!/usr/bin/env bash

set -euo pipefail

function environment {
    APP_NAME="acikgozb-dev"

    AWS_PROFILE="${AWS_PROFILE:-default}"
    AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text --profile "$AWS_PROFILE")

    TF_BACKEND_STATE_BUCKET="terraform-$AWS_ACCOUNT_ID"    
    TF_BACKEND_KEY="apps/$APP_NAME.tfstate"

    echo "APP_NAME:$APP_NAME AWS_ACCOUNT_ID:$AWS_ACCOUNT_ID TF_BACKEND_STATE_BUCKET:$TF_BACKEND_STATE_BUCKET TF_BACKEND_KEY:$TF_BACKEND_KEY"
}

function init {
    terraform init \
        -backend-config region="$AWS_REGION" \
        -backend-config bucket="$TF_BACKEND_STATE_BUCKET" \
        -backend-config key="$TF_BACKEND_KEY" 
}

function generate_artifacts {
    cd ./scripts/redirect-worker

    npm ci
    wrangler deploy --outdir ./out --config ./wrangler.toml --dry-run

    REDIRECT_WORKER_PATH="./scripts/redirect-worker/out/index.js"

    cd - > /dev/null
}

function plan {
    generate_artifacts

    cat > ./terraform.tfvars <<-_EOF
app_name="$APP_NAME"
redirect_worker_path="$REDIRECT_WORKER_PATH"
frontend_asset_path="$FRONTEND_ASSET_PATH"
_EOF

    terraform plan -var-file ./terraform.tfvars -out ./tfplan 
}

function apply {
    terraform apply ./tfplan
}

"$@"
